### ISSUE TITLE
Use arrow keys to toggle colors 

### ISSUE THREAD

**Issue by manu-chroma** [gyanl/A-Color-A-Day#13]
User should be able to toggle between different colors using left and right arrow keys. 

![image](https://cloud.githubusercontent.com/assets/12952080/19048973/1780f76a-89c6-11e6-91ab-3269b2fc3273.png)

Some other key shortcuts have already been implemented.   Reference: https://github.com/gyanl/ChromaGen/issues/11  
[CONTRIBUTING.md](https://github.com/gyanl/ChromaGen/blob/gh-pages/CONTRIBUTING.md)

**Comment by NielsKornerup** [comment]
I am interested in working on this.

**Comment by manu-chroma** [comment]
@NielsKornerup go ahead! :+1:

**Comment by sabinmarcu** [comment]
Added a PR with a possible fix. Can alter if you want something else from it.

**Comment by NielsKornerup** [comment]
I have something that works nicely, but I think there is a bug with copying to clipboard using buttons. I will fix this and then push my changes to my fork.

**Comment by NielsKornerup** [comment]
I have implemented the colour transitions, but the clipboard is still not working. [This](http://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript) suggests that we ask the user to copy/paste themselves, since most browsers try to prevent users from modifying the clipboard.

**Comment by gyanl** [comment]
@NielsKornerup : @collnwalkr's patch managed to get the keyboard copy shortcut working, so I merged that commit. This issue is now resolved. Thanks!
